version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./app/.env

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./app/.env

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data: