"""Initial migration

Revision ID: 12b41b0e5b5b
Revises: 7c138b4f4204
Create Date: 2025-04-06 09:22:28.065684

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12b41b0e5b5b"
down_revision: Union[str, None] = "7c138b4f4204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "secrets",
        "secret_key",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=360),
        existing_comment="Уникальный ключ доступа к секрету",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "secrets",
        "secret_key",
        existing_type=sa.String(length=360),
        type_=sa.VARCHAR(length=36),
        existing_comment="Уникальный ключ доступа к секрету",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
