"""Initial migration

Revision ID: 452b1703972c
Revises: f43e72e6bca1
Create Date: 2025-04-05 23:59:04.237940

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "452b1703972c"
down_revision: Union[str, None] = "f43e72e6bca1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
