"""Initial migration

Revision ID: 5a02f346b304
Revises: c8fdf5f65687
Create Date: 2025-04-06 03:57:47.699834

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "5a02f346b304"
down_revision: Union[str, None] = "c8fdf5f65687"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
