"""Initial migration

Revision ID: 9d8bbc63db42
Revises: f29a7f349311
Create Date: 2025-04-06 00:13:57.459568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8bbc63db42'
down_revision: Union[str, None] = 'f29a7f349311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('ttl_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secrets', 'ttl_seconds')
    # ### end Alembic commands ###
