"""Initial migrationccc

Revision ID: c8fdf5f65687
Revises: 83ff5e07bbab
Create Date: 2025-04-06 00:31:44.818794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8fdf5f65687"
down_revision: Union[str, None] = "83ff5e07bbab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "secrets",
        "id",
        existing_type=sa.INTEGER(),
        comment="Уникальный идентификатор секрета",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "secrets",
        "secret",
        existing_type=sa.TEXT(),
        comment="Конфиденциальные данные, хранимые в секрете",
        existing_nullable=False,
    )
    op.alter_column(
        "secrets",
        "passphrase",
        existing_type=sa.VARCHAR(length=255),
        comment="Опциональная фраза-пароль для дополнительной защиты",
        existing_nullable=True,
    )
    op.alter_column(
        "secrets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время создания секрета",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "secrets",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Абсолютное время истечения срока действия секрета",
        existing_nullable=True,
    )
    op.alter_column(
        "secrets",
        "ttl_seconds",
        existing_type=sa.INTEGER(),
        comment="Время жизни секрета в секундах от момента создания",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "secrets",
        "ttl_seconds",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Время жизни секрета в секундах от момента создания",
        existing_nullable=True,
    )
    op.alter_column(
        "secrets",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Абсолютное время истечения срока действия секрета",
        existing_nullable=True,
    )
    op.alter_column(
        "secrets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Время создания секрета",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "secrets",
        "passphrase",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Опциональная фраза-пароль для дополнительной защиты",
        existing_nullable=True,
    )
    op.alter_column(
        "secrets",
        "secret",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Конфиденциальные данные, хранимые в секрете",
        existing_nullable=False,
    )
    op.alter_column(
        "secrets",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Уникальный идентификатор секрета",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
