"""Initial migration

Revision ID: f43e72e6bca1
Revises: 411e7e8d5e68
Create Date: 2025-04-05 23:58:28.881303

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "f43e72e6bca1"
down_revision: Union[str, None] = "411e7e8d5e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
